### ISSUE TITLE
using :strict and not having `file` available should complain loudly

### ISSUE THREAD

**Issue by ossareh** [musaffa/file_validators#13]
Many docker images have a minimal set of tools, in the case of the jruby docker image `file` is not available by default. In this case there is a very quiet note from file_validators and the `content_type` check returns an `octet-stream`. If you're using :strict and the command fails because the command cannot be found, that failure should occur very obviously. Currently a "file: not found" log line occurs, I suggest that it should be an exception.

Code in question: https://github.com/musaffa/file_validators/blob/b66db8aa20c473e36c0aefd19a30d0bf6e19aac5/lib/file_validators/utils/content_type_detector.rb#L50

**Comment by musaffa** [comment]
[mimemagic](https://github.com/minad/mimemagic) is a ruby implementation of detecting file's media type by magic numbers. It may be slow in comparison to C-implementation of `file` command. But we can support both and let users decide which library they want to use in strict mode.

**Comment by ossareh** [comment]
I much prefer not relying on unix commands when it comes to portability, mimemagic sounds like the right option in that regard. However, if choosing the Cocaine route to run `file` I still believe failing to find the command should result in a "loud" exception.

**Comment by musaffa** [comment]
The reason behind returning a default media type after failure is that when you use strict mode it will eventually fail during the validation of content/media type. Rather than raising an exception that can crush the application, an input field error is returned.

Currently the master branch logs the failure.

**Comment by ossareh** [comment]
Oh, I see. I'm not super familiar with the way validators work - thanks for
helping me understand that. Perhaps the logging needs to be more aggressive
then, while debugging this issue I was seeing "file: not found" - and
thinking I had an issue with where carrierwave was putting my file. I
wasn't reading it as `file` the command was not being found.

**Comment by musaffa** [comment]
Yes, this gem requires much better logger integration so that the developer can see all the stack trace in the console during failure.
