### ISSUE TITLE
Not working for multiple file uploads

### ISSUE THREAD

**Issue by aried3r** [musaffa/file_validators#14]
Carrierwave has the ability to [upload multiple files](https://github.com/carrierwaveuploader/carrierwave#multiple-file-uploads). I just tried if file_validators still work with that, but it doesn't seem to, using the following code:

``` Ruby
mount_uploaders :documents, DocumentUploader
validates :documents, file_size: { less_than_or_equal_to: 100.kilobytes }
```

and I was able to upload an image over 1MB. Is there support being planned for this?

**Comment by aried3r** [comment]
Maybe I should specify: I want individual files to be less than or equal to a certain size, the total size of all files is of no interest, either way, none of it worked :)

**Comment by musaffa** [comment]
Currently `file_validator` doesn't support multiple files per attribute. I will try to add this feature. Would also love to get a pull request if you want to contribute.
