### ISSUE TITLE
Active Storage uploads failed

### ISSUE THREAD

**Issue by mayeco** [musaffa/file_validators#26]
Using Active Storage failed using file size validators

**Comment by musaffa** [comment]
Can you please share the stack trace here?

**Comment by mayeco** [comment]
The object passed as in the variable `value` don't have a size method in validate_each(record, attribute, value) 

`undefined method size for #<ActiveStorage::Attached::One:0x00007fd2e0eca3a0>`

`activesupport (5.2.0.rc2) lib/active_support/core_ext/module/delegation.rb:275:in `method_missing'
file_validators (2.1.0) lib/file_validators/validators/file_size_validator.rb:21:in `block in validate_each'
file_validators (2.1.0) lib/file_validators/validators/file_size_validator.rb:18:in `each'
file_validators (2.1.0) lib/file_validators/validators/file_size_validator.rb:18:in `validate_each'
activemodel (5.2.0.rc2) lib/active_model/validator.rb:152:in `block in validate'
activemodel (5.2.0.rc2) lib/active_model/validator.rb:149:in `each'
activemodel (5.2.0.rc2) lib/active_model/validator.rb:149:in `validate'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:605:in `catch'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:605:in `block in default_terminator'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:199:in `block in halting'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:513:in `each'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:131:in `run_callbacks'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:816:in `_run_validate_callbacks'
activemodel (5.2.0.rc2) lib/active_model/validations.rb:409:in `run_validations!'
activemodel (5.2.0.rc2) lib/active_model/validations/callbacks.rb:118:in `block in run_validations!'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:98:in `run_callbacks'
activesupport (5.2.0.rc2) lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
activemodel (5.2.0.rc2) lib/active_model/validations/callbacks.rb:118:in `run_validations!'
activemodel (5.2.0.rc2) lib/active_model/validations.rb:339:in `valid?'
activerecord (5.2.0.rc2) lib/active_record/validations.rb:67:in `valid?'
activerecord (5.2.0.rc2) lib/active_record/validations.rb:84:in `perform_validations'
activerecord (5.2.0.rc2) lib/active_record/validations.rb:46:in `save'
activerecord (5.2.0.rc2) lib/active_record/transactions.rb:310:in `block (2 levels) in save'
activerecord (5.2.0.rc2) lib/active_record/transactions.rb:386:in `block in with_transaction_returning_status'`

**Comment by musaffa** [comment]
Would you like to submit a Pull Request to solve this issue? I would love to accept one.

**Comment by IvanGrgurevic** [comment]
Hi @musaffa this issue it preventing us to use this gem with Active Storage. We would appreciate it if PR #27 could be merged and released ASAP.

**Comment by mayeco** [comment]
thanks @musaffa can you please do create a release.

**Comment by musaffa** [comment]
Done.
