### ISSUE TITLE
ArgumentError: Unknown validator: 'FileContentTypeValidator'

### ISSUE THREAD

**Issue by paulmthiebauth** [musaffa/file_validators#33]
Hello!

I'm currently migrating an application from PaperClip to ActiveStorage. As part of thoughtbots migration guide, they suggested using your gem. Our model, lets call it 'Organization' like they do in the example, has a 'logo' attached to it. Using their migration guide, I added the following to the Organization model:

```
  validates :logo, file_content_type: {
    allow: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'],
    if: -> { logo.attached? },
  }
```

I expected this to work out of the box, which it does when I'm uploading a file. If I remove say jpeg from the list and try to upload a jpeg, I get an error. The problem is that when I try to run basically anything else in console, like Organization.find(ID) or try to delete a record for example, I get the error mentioned in the title: 

ArgumentError: Unknown validator: 'FileContentTypeValidator'
/gems/activemodel-5.2.1/lib/active_model/validations/validates.rb:121:in `rescue in block in validates'

Our app is running on Rails 5.2
Please let me know if you can help or if we should take an alternative approach, thanks!

**Comment by musaffa** [comment]
It looks like file content type validator is not loaded in that case. After you explicitly require file_validators gem in your console, do you still see this problem popping up?

**Comment by paulmthiebauth** [comment]
```[1] pry(main)> require 'file_validators'
LoadError: cannot load such file -- file_validators
from /Users/paulthiebauth/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'```

**Comment by paulmthiebauth** [comment]
```[1] pry(main)> require 'file_validators'
LoadError: cannot load such file -- file_validators
from /Users/paulthiebauth/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'```

Gem is in our Gemfile and Gemfile.lock, your suggestion doesnt seem to be working unfortunately

**Comment by paulmthiebauth** [comment]
Were going to write our own validations as the recommended approach in the Paperclip -> ActiveStorage guide appears to still create a new ActiveStorage::Attachment record even when the validation fails which overrides the original image on update.

**Comment by t-bello7** [comment]
Add gem 'active_storage_validations' to the Gemfile. This might be pretty late but I just started working with rails and it took me a while to figure out.
You can also check the documentation out.
https://github.com/igorkasyanchuk/active_storage_validations
