### ISSUE TITLE
Dependency on cocaine gem still in 2.3.0

### ISSUE THREAD

**Issue by jedrekdomanski** [musaffa/file_validators#36]
Although a merge request has been merged and the readme already mentions `terrapin` gem as a dependency when using `mode: :strict` I still get a warning pointing at dependency on `cocaine` gem which is deprecated: 
`file_validators requires 'cocaine' gem as you are using file content type validations in strict mode`
from [here](https://github.com/musaffa/file_validators/pull/29/commits/317b2163178ea50ef6b95817daca9eb38584c5e3#diff-ae1b13cc2e39b36193b11be90f2edeb7L6)
I checked the latest version on [rubygems.org](rubygems.org) and it seems to be at version 3.0.1 beta.
`bundle update file_validators` returns `Bundler attempted to update file_validators but its version stayed the same`

Gemfile.lock
`file_validators (2.3.0)`

Is it possible to upgrade it?

**Comment by musaffa** [comment]
@jedrekdomanski Give me a few days, I'll update the gem. Have you tried the master branch? Does it work well for you?

**Comment by jedrekdomanski** [comment]
Yes, it does work with master branch, @musaffa .
```
gem 'terrapin'
# gem 'cocaine', '~> 0.5.8'
gem 'file_validators', git: 'git@github.com:musaffa/file_validators.git', branch: 'master'
```
It looks like the latest gem version is `2.3.0` and the master branch that includes this fix is at `3.0.0.beta1`. It would be nice if I didn't have to explicitly point to master branch to install the latest version.

**Comment by musaffa** [comment]
Sounds great! Right now I'm in holiday. I'll try to publish the gem in the next week.

**Comment by kennwilson** [comment]
I'd like to bring a little attention to this issue again. The current version of file_validator is still at 2.3.0, the version suffering from this Cocaine dependency (haha).

I also have a strong preference for not pointing to master branches on Github in my Gemfile. Any chance we can see this fix in a new 2.3.1 gem?

**Comment by musaffa** [comment]
Hi, sorry for my late response to this issue. I'll try to resolve this today. Thanks for your patience.

**Comment by musaffa** [comment]
Hi, I've released a new version. This release includes #32 and #37. PR #32 removes the need for `terrapin` gem. It adds options for different mime type analyzers. Check the new `:tool` option of Content Type Validator in the README for more information.

Since this is a major change, the new release is still a beta release: 3.0.0.beta2. Please give it a check. It should be a backward compatible release with `2.3.0`. If no issue arises after some people using it, I will cut a stable 3.0.0 release.

Thank you.

**Comment by musaffa** [comment]
3.0.0 has been released. Thanks for your patience.

**Comment by letiesperon** [comment]
thank you @musaffa!!!!!

**Comment by kennwilson** [comment]
Thanks!
