### ISSUE TITLE
3.0.0 stable release?

### ISSUE THREAD

**Issue by gael-ian** [musaffa/file_validators#38]
Hi @musaffa,

What's missing for a 3.0.0 stable release? I can see a few outdated issues in here, just waiting to be closed, and some staled PR but what did you expect to put into the stable 3.0.0 before you release it?

Maybe I can help you to reach that goal.

**Comment by gael-ian** [comment]
Can you explain what's missing with this PR? I can see you approved it months ago, there's unit tests to cover the changes and it can be merged straight forwardly. Plus, I don't see how I can contribute to someone else's PR.

Maybe you can merge it into master and open an issue (or more) to describe what you'd like to do before the beta release?

**Comment by musaffa** [comment]
Can you please test that branch to see whether it works for real?

**Comment by gael-ian** [comment]
I checked out the code and can see no problem. I'll try to use it in a real world project and see how it fits.

**Comment by gael-ian** [comment]
Hello @musaffa 

I went further on testing PR #32 today.

### 1. Unit and Integration tests

Using Ruby 2.5.0 (as specified in your `.travis.yml`) and a default `bundle install` (hence activemodel 6.0.2.2 and mime-types 3.3.1), unit tests and integration tests run without any problems.

### 2. Appraisal tests

I tried to run tests with Appraisal but there's some issues, due to the lack of support for rbenv in Appraisal and the multiple ruby versions required to run the tests properly. So I ended updating your Appraisal and your Travis configurations to let Travis CI run those tests for me. (Those changes will be sent in a new Pull Request.)

I had no problems except for tests runned with JRuby 9.2, that froze without reasons.

### 3. Real world application

I then tried to use the `mime-type-analyzer` branch in a real world project, validating attachments in a contact form. Files where effectively refused when they were not of the right type or exceeded the maximum size.

So as far as I can see, I would say PR #32 is totally fine to be merged in master.

**Comment by gael-ian** [comment]
I just tried to run unit and integration tests with JRuby 9.2.9.0 on my machine and they all passed. It's still extremely slow compared to C Ruby versions (file loading take 60 times longer!) but except a few warnings about the debug option and code coverage inaccuracy without it, nothing wrong is reported.

So it seems to be all green :+1:

**Comment by musaffa** [comment]
`3.0.0` has been released. Thanks for your patience.
